version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/bon-appetit # Cambia esto a la ruta de tu proyecto
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root